backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"  # Carpeta para almacenar imágenes
public_folder: "/images/uploads"

collections:
  - name: "propiedades"
    label: "Propiedades"
    folder: "data"
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Precio", name: "precio", widget: "string" }
      - { label: "Ubicación", name: "ubicacion", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Imágenes", name: "imagenes", widget: "list", field: { label: "Imagen", name: "imagen", widget: "image" } }
